[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd backend && npm install", "cd ../frontend && npm install && npm run build"]

[phases.build]
cmds = ["mkdir -p backend/public", "cp -r frontend/build/* backend/public/"]

[start]
cmd = "cd backend && npm start"