[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
    "npm install --prefix backend",
    "npm install --prefix frontend"
]

[phases.build]
cmds = [
    "npm run build --prefix frontend",
    "mkdir -p backend/public",
    "cp -r frontend/build/* backend/public/"
]

[start]
cmd = "npm start --prefix backend"